<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>

<!DOCTYPE teplad [
  <!ELEMENT teplad (xml_url,name,date_update,version,date_version,coder,tags,url,compatibility,php_ver,license,descriptions,screenshots,logo) >
    <!ELEMENT url (download_url,coder_url,demo_url) >
    <!ELEMENT descriptions (description+) >
    <!ELEMENT screenshots (screenshot*) >
    
    <!ELEMENT xml_url			(#PCDATA) >
    <!ELEMENT name				(#PCDATA) >
    <!ELEMENT date_update		(#PCDATA) >
    <!ELEMENT version			(#PCDATA) >
    <!ELEMENT date_version		(#PCDATA) >
    <!ELEMENT coder				(#PCDATA) >
    <!ELEMENT tags				(#PCDATA) >
    <!ELEMENT compatibility		(#PCDATA) >
    <!ELEMENT php_ver			(#PCDATA) >
    <!ELEMENT license			(#PCDATA) >
    <!ELEMENT logo				(#PCDATA) >
    
    <!ELEMENT download_url		(#PCDATA) >
    <!ELEMENT coder_url			(#PCDATA) >
    <!ELEMENT demo_url			(#PCDATA) >
    <!ELEMENT description		(#PCDATA|br|ol|ul|li|i|b)* >
    <!ELEMENT br					EMPTY >
    <!ELEMENT ol					(li+) >
    <!ELEMENT ul					(li+) >
    <!ELEMENT li				(#PCDATA) >
    <!ELEMENT i					(#PCDATA) >
    <!ELEMENT b					(#PCDATA) >
    <!ELEMENT screenshot		(#PCDATA) >
    
    <!ATTLIST teplad version CDATA	#REQUIRED >
    <!ATTLIST name type	(plugin|template|addon) #REQUIRED >
    <!ATTLIST description lang NMTOKEN	#REQUIRED >
    <!ATTLIST screenshot view CDATA		#REQUIRED >
]>

<!-- Do note change the Element teplad! -->
<teplad version="1.1">
  <!-- the URL form this xml-file -->
  <!-- full URL with http(s) -->
  <xml_url>https://raw.githubusercontent.com/cmb69/monorder_xh/master/teplad.xml</xml_url>
  <!-- Attribute type for Data type: plugin, template or addon -->
  <!-- the name of the Plugin -->
  <name type="plugin">Monorder_XH</name>
  <!-- Date this xml-file was updated, yyyy.mm.dd -->
  <date_update>2021.01.23</date_update>
  <!-- version of Plugin -->
  <version>1.1</version>
  <!-- date of publication, yyyy.mm.dd -->
  <date_version>2019.01.24</date_version>
  <!-- the name of the programmer -->
  <coder>Christoph M. Becker</coder>
  <!-- Categories must be written in lower case. More than one possible, separated by comma without spaces. -->
  <!-- Plugin Categories, i.e. audio,video,datenschutz,socialmedia,system,admin,backup,calendar,form,seo. -->
  <!-- Template Categories, i.e. cssonly,onepage. -->
  <!-- You can currently define your own tags. These are displayed, but not filtered. -->
  <!-- All available categories can be found on the website. -->
  <tags>booking,form</tags>
  <!-- full URLs with http(s) -->
  <url>
    <!-- URL where you can download the plugin -->
    <!-- If there no Download-URL, enter this follows! - <download_url></download_url> -->
    <download_url>https://github.com/cmb69/monorder_xh/releases/1.1</download_url>
    <!-- URL of the programmer's website -->
    <!-- If there no Website, enter this follows! - <coder_url></coder_url> -->
    <coder_url>https://3-magi.net</coder_url>
    <!-- URL where find a demo -->
    <!-- If there no Demo-Website, enter this follows! - <demo_url></demo_url> -->
    <demo_url></demo_url>
  </url>
  <!-- compatibility with versions of XH, i.e. 1.6, 1.6.7 - 1.7.2, ≥ 1.7, ... -->
  <compatibility>≥ 1.5.4</compatibility>
  <!-- minimum version of PHP that is required, i.e. 5.3, 5.6, 7, ≥ 5.6, ... -->
  <!-- If there no specification, e.g. for templates, enter this follows! - <php_ver></php_ver> -->
  <php_ver>≥ 5.1.0</php_ver>
  <!-- the License for the Plugin, GPLv3, AGPL, LGPL, GPLv2 ... -->
  <license>GPLv3</license>
  <!-- Description in English is mandatory -->
  <descriptions>
    <!-- description of the plugin, ca. 200 characters, you can use <br/>, <ol></ol>, <ul></ul>, <li></li>, <b></b>, <i></i>. -->
    <description lang="en">
      Monorder_XH facilitates placing order or reservation forms for single items and events
      (hence the name which is a synaeresis of "mono" and "order") on your website.
      Ordering resp. booking takes in account the number of items on stock resp. the free places,
      so overbooking is not possible.
      The forms have to be created with Advancedform_XH,
      and it is possible to use a single form for multiple sales items resp. events.
      However, it is only possible to offer one form for a particular item resp. event on each page,
      so if you have more demanding needs use a shopping resp. a booking system.
      Besides its actual use, Monorder_XH serves to demonstrate the possibilities
      and limitations of using Advancedform_XH's hook system for custom plugins.
    </description>
    <!-- Beschreibung des Plugins, ca. 200 Zeichen, es können <br/>, <ol></ol>, <ul></ul>, <li></li>, <b></b>, <i></i> genutzt werden. -->
    <description lang="de">
      Monorder_XH ermöglicht die Platzierung von Bestell- oder Reservierungsformularen
      für einzelne Posten bzw. Veranstaltungen (daher der Name, der eine Kontraktion
      von "mono" und "order", engl. für Bestellung, ist) auf Ihrer Website.
      Bei Bestellungen bzw. Reservierungen werden dabei der verfügbare Bestand bzw.
      die freien Plätzen berücksichtigt, so dass Überbuchungen nicht möglich sind.
      Die Formulare müssen mit Advancedform_XH erstellt werden,
      und es ist möglich ein einziges Formular für mehrere Verkaufsartikel bzw. Veranstaltungen zu verwenden.
      Allerdings kann höchstens ein Formular für einen einzigen Verkaufsartikel bzw.
      eine Veranstaltung pro Seite genutzt werden,
      so dass Sie ein Einkaufs- bzw. Reservierungsystem verwenden sollten, wenn Sie erweiterte Ansprüche haben.
      Abgesehen von seinem eigentlichen Verwendungszweck dient Monorder_XH auch
      zur Demonstration der Möglichkeiten und Beschränkungen der Verwendung des Hook-Systems
      von Advancedform_XH für maßgeschneiderte Plugins.
    </description>
    <!-- additional languages are possible, i.e. da, fr, pl, ... -->
    <!-- The use of this language is limited by the website where the repository is hosted. -->
  </descriptions>
  <!-- If there no screenshots, enter this follows! - <screenshots></screenshots> -->
  <screenshots/>
  <!-- full URL with http(s) -->
  <!-- , use only .gif, .jpg, .jpeg, .png or .svg! -->
  <!-- The use of this different image formats is dependent on the configuration of the repository. -->
  <!-- If there no logo, enter this follows! - <logo></logo> -->
  <logo>https://raw.githubusercontent.com/cmb69/monorder_xh/master/monorder.png</logo>
</teplad>
<!-- Ich versichere, dass ich für alle angegebenen Texte und / oder Bilder die Urheberrechte besitze, oder eine entsprechende Nutzungsgenehmigung vorweisen kann. -->
<!-- I guarantee, that I have the copyright for all texts and / or pictures, or can show a corresponding permission for their use. -->
